name: builds

on:
  - push
  - pull_request

permissions: read-all

env:
  DEFAULT_CFLAGS: "-Wall -Wextra -Werror -Wno-unused-parameter -Wno-unused-function"

  # Apt sometimes likes to ask for user input, this will prevent that.
  DEBIAN_FRONTEND: "noninteractive"

jobs:
  centos-7:
    name: CentOS 7
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - name: Install system dependencies
        run: |
          yum -y install epel-release
          yum -y install \
                autoconf \
                automake \
                gcc \
                tar \
                libnetfilter_log-devel \
                libmnl-devel \
                libnetfilter_conntrack-devel \
                make \
                ncurses-devel \
                pkgconfig \
                sudo \
                which
      - run: ./autogen.sh
      - run: CFLAGS="${DEFAULT_CFLAGS}" ./configure
      - run: make -j2
      - run: make install
      - run: make distcheck
      - run: vuurmuur -V
