name: builds

on:
  - push
  - pull_request

permissions: read-all

env:
  DEFAULT_CFLAGS: "-Wall -Wextra -Werror -Wno-unused-parameter -Wno-unused-function"

  # Apt sometimes likes to ask for user input, this will prevent that.
  DEBIAN_FRONTEND: "noninteractive"

jobs:
  ubuntu-2004:
    name: Ubuntu 20.04
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Install system dependencies
        run: |
            apt update
            apt-get upgrade -y
            apt-get -y install make \
                autoconf \
                build-essential \
                autoconf \
                automake \
                dpkg-dev \
                debhelper \
                libtool \
                make \
                pkg-config \
                libnetfilter-conntrack-dev \
                libnetfilter-log-dev \
                libmnl-dev \
                libncurses5-dev \
                libncursesw5-dev
      - run: ./autogen.sh
      - run: CFLAGS="${DEFAULT_CFLAGS}" ./configure --prefix=/usr --sysconfdir=/etc
      - run: make -j2
      - run: make install
      - run: make distcheck
      - run: vuurmuur -V
      - run: dpkg-buildpackage

  ubuntu-2204:
    name: Ubuntu 22.04
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Install system dependencies
        run: |
            apt update
            apt-get upgrade -y
            apt-get -y install make \
                autoconf \
                build-essential \
                autoconf \
                automake \
                dpkg-dev \
                debhelper \
                libtool \
                make \
                pkg-config \
                libnetfilter-conntrack-dev \
                libnetfilter-log-dev \
                libmnl-dev \
                libncurses5-dev \
                libncursesw5-dev
      - run: ./autogen.sh
      - run: CFLAGS="${DEFAULT_CFLAGS}" ./configure --prefix=/usr --sysconfdir=/etc
      - run: make -j2
      - run: make install
      - run: make distcheck
      - run: vuurmuur -V
      - run: dpkg-buildpackage

  ubuntu-2204-installer:
    name: Ubuntu 22.04 Installer
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Install system dependencies
        run: |
            apt update
            apt-get upgrade -y
            apt-get -y install make \
                autoconf \
                build-essential \
                autoconf \
                automake \
                libtool \
                gettext \
                make \
                pkg-config \
                libnetfilter-conntrack-dev \
                libnetfilter-log-dev \
                libmnl-dev \
                libncurses5-dev \
                libncursesw5-dev
      - run: installer/install.sh --defaults --install --build-update
      - run: installer/install.sh --defaults --upgrade --build-update

  ubuntu-2404-sb:
    name: Ubuntu 24.04 scan-buid
    runs-on: ubuntu-latest
    container: ubuntu:24.04
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Install system dependencies
        run: |
            apt update
            apt-get upgrade -y
            apt-get -y install make \
                autoconf \
                build-essential \
                autoconf \
                automake \
                clang-tools-18 \
                python3-clang-18 \
                dpkg-dev \
                debhelper \
                libtool \
                make \
                pkg-config \
                libnetfilter-conntrack-dev \
                libnetfilter-log-dev \
                libmnl-dev \
                libncurses5-dev \
                libncursesw5-dev
      - run: ./autogen.sh
      - run: CC=clang-18 CFLAGS="${DEFAULT_CFLAGS}" scan-build-18 ./configure --with-widec=no
      - run: CC=clang-18 scan-build-18 --status-bugs make -j2
      - run: make clean
      - run: CC=clang-18 CFLAGS="${DEFAULT_CFLAGS}" scan-build-18 ./configure --with-widec=yes
      - run: CC=clang-18 scan-build-18 --status-bugs make -j2

  centos-7:
    name: CentOS 7
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Install system dependencies
        run: |
          yum -y install epel-release
          yum -y install \
                autoconf \
                automake \
                gcc \
                gettext-devel \
                tar \
                libnetfilter_log-devel \
                libmnl-devel \
                libnetfilter_conntrack-devel \
                libtool \
                make \
                ncurses-devel \
                pkgconfig \
                sudo \
                which
      - run: ./autogen.sh
      - run: CFLAGS="${DEFAULT_CFLAGS} -std=gnu99" ./configure --prefix=/usr --sysconfdir=/etc
      - run: make -j2
      - run: make install
      - run: make distcheck
      - run: ldconfig /usr/lib
      - run: vuurmuur -V
